version: '3.8'

services:
 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: video-proctoring-backend
    ports:
      - "5000:5000"
   
    
    volumes:
      - ./backend/uploads:/app/uploads
    env_file:
    - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: video-proctoring-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_SOCKET_URL=http://localhost:5000

